server:
  port: 8080
spring:
  application:
    name: gateway-service
  autoconfigure:
    # TODO: remove when fixed https://github.com/spring-projects/spring-security/issues/6314
    exclude: org.springframework.boot.actuate.autoconfigure.security.reactive.ReactiveManagementWebSecurityAutoConfiguration
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: uaa
            client-id: admin
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid,profile,email,resource.read,resource.write
       
        provider:
          uaa:
            authorization-uri: http://localhost:8888/uaa/oauth/authorize
            token-uri: http://localhost:8888/uaa/oauth/token
            user-info-uri: http://localhost:8888/uaa/userinfo
            user-name-attribute: sub
            jwk-set-uri: http://localhost:8888/uaa/token_keys
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie  
        - id: device-service
          uri: lb://DEVICE-SERVICE
          predicates:
            - Path=/device/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie  
        - id: backup-service
          uri: lb://BACKUP-SERVICE
          predicates:
            - Path=/backup/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie  
        - id: NOTIFICATION-SERVICE
          uri: lb://notification-service
          predicates:
            - Path=/notification/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie              
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone : http://${eureka.instance.hostname}:8761/eureka/  